version: "3.7"

services:
  influxdb:
    image: library/influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - tsm
    environment:
      INFLUXDB_DB: ${INFLUX_DB}

  mongodb:
    image: library/mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - tsm

  tsm:
    env_file:
      - .env
    environment:
      - INFLUX_HOST=influxdb
      - MONGO_HOST=mongodb
    build: .
    container_name: tsm
    ports:
      - ${TSM_PORT}:${TSM_PORT}
    networks:
      - tsm
    restart: on-failure

networks:
  tsm:
    driver: "bridge"