version: "3.7"

services:
  influxdb:
    image: library/influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - tsm
    environment:
      INFLUXDB_DB: ${INFLUX_DB}

  rabbitmq:
    image: library/rabbitmq:3.8.9
    container_name: rabbitmq
    ports:
      - 5672:5672
    networks:
      - tsm

  tsm:
    build: .
    env_file:
      - .env
    environment:
      - INFLUX_HOST=influxdb
      - RABBIT_HOST=rabbitmq
    container_name: tsm
    depends_on:
      - influxdb
      - rabbitmq
    ports:
      - ${TSM_PORT}:${TSM_PORT}
    networks:
      - tsm
    restart: on-failure

networks:
  tsm:
    driver: "bridge"